apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: clone-repo-cloud-function
  namespace: '613847488004'
  selfLink: /apis/serving.knative.dev/v1/namespaces/613847488004/services/clone-repo-cloud-function
  uid: 7ec964bc-2885-4b38-ac8f-77228982d441
  resourceVersion: AAYj59M8QP4
  generation: 2
  creationTimestamp: '2024-10-07T19:14:01.759741Z'
  labels:
    gcb-trigger-id: 5888f64a-db49-4ad3-b987-33a06ce5b899
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-region: global
    run.googleapis.com/satisfiesPzs: 'true'
    cloud.googleapis.com/location: asia-south1
  annotations:
    serving.knative.dev/creator: arvindchavan528980@gmail.com
    serving.knative.dev/lastModifier: arvindchavan528980@gmail.com
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/operation-id: efd3eb73-400c-41da-b35e-a21e5905c64f
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '1'
    run.googleapis.com/urls: '["https://clone-repo-cloud-function-613847488004.asia-south1.run.app","https://clone-repo-cloud-function-cer2tt6juq-el.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 613847488004-compute@developer.gserviceaccount.com
      containers:
      - name: placeholder-1
        image: gcr.io/cloudrun/placeholder
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 2
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-10-07T19:14:08.622846Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2024-10-07T19:14:01.828890Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2024-10-07T19:14:08.592113Z'
  latestReadyRevisionName: clone-repo-cloud-function-00001-shz
  latestCreatedRevisionName: clone-repo-cloud-function-00001-shz
  traffic:
  - revisionName: clone-repo-cloud-function-00001-shz
    percent: 100
    latestRevision: true
  url: https://clone-repo-cloud-function-cer2tt6juq-el.a.run.app
  address:
    url: https://clone-repo-cloud-function-cer2tt6juq-el.a.run.app
