steps:
# ... (previous steps remain the same)

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy workflow-agent \
      --image gcr.io/$PROJECT_ID/workflow-agent \
      --platform managed \
      --region us-central1 \
      --allow-unauthenticated \
      --set-env-vars=BUCKET_NAME=cloud-function-alert-$PROJECT_ID,GEMINI_API_KEY=$_GEMINI_API_KEY

images:
- 'gcr.io/$PROJECT_ID/workflow-agent'

substitutions:
  _GEMINI_API_KEY: ${_GEMINI_API_KEY}