steps:
# Print the contents of the current directory
- name: 'ubuntu'
  args: ['ls', '-la']

# Print the contents of the src directory
- name: 'ubuntu'
  args: ['ls', '-la', 'src']

# Print Node.js and npm versions
- name: 'node:16'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    node --version
    npm --version

# Install dependencies
- name: 'node:16'
  entrypoint: 'npm'
  args: ['install']
  dir: 'src'

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-function', '.']

# Deploy cloneRepoToStorage function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy cloneRepoToStorage \
      --trigger-http \
      --runtime=nodejs16 \
      --entry-point=cloneRepoToStorage \
      --source=src \
      --allow-unauthenticated

# Deploy analyzeCode function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy analyzeCode \
      --trigger-http \
      --runtime=nodejs16 \
      --entry-point=analyzeCode \
      --source=src \
      --allow-unauthenticated

images:
- 'gcr.io/$PROJECT_ID/my-function'