steps:
# Print working directory contents
- name: 'ubuntu'
  args: ['ls', '-la']

# Print src directory contents
- name: 'ubuntu'
  args: ['ls', '-la', 'src']

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/workflow-agent', '.']

# Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/workflow-agent']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -ex
    echo "Deploying to Cloud Run..."
    gcloud config set project $PROJECT_ID
    gcloud config set run/region us-central1
    gcloud run deploy workflow-agent \
      --image gcr.io/$PROJECT_ID/workflow-agent \
      --platform managed \
      --allow-unauthenticated \
      --set-env-vars=BUCKET_NAME=cloud-function-alert-$PROJECT_ID,GEMINI_API_KEY=$_GEMINI_API_KEY
    echo "Deployment completed."

images:
- 'gcr.io/$PROJECT_ID/workflow-agent'

substitutions:
  _GEMINI_API_KEY: ${_GEMINI_API_KEY}